<H1 style="text-align: center; color:black;"> Project - Movie Dataset</H1>

<br>
<H2 style="text-align: center; color:black;">Project Scope </h2>
<br>
<H3 style="text-align: justify; color:black;">The project is divided into two main parts:</h3>
<br>
<H3 style="text-align: left; color:black;">1. Data Cleaning </h3>
<H3 style="text-align: justify; color:black;">Exploring, cleaning and saving the dataset into a new file.</h3>
<br>
<H3 style="text-align: left; color:black;">2. Exploratory Data Analysis with modified dataset </h3>
<br>


<H2 style="text-align: center; color:black;">Dataset </h2>
<br>
<H2 style="text-align: left; color:black;">Context </h2>

The dataset contains metadata for 45,000 entries of movie information listed in the Full MovieLens Dataset.

<br>

<H2 style="text-align: left; color:black;">Acknowledgements </h2>

Dataset downloaded from [Kaggle](https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset)
which is an ensemble of data collected from The Movie Data Base using [TMDB Open API](https://developer.themoviedb.org/docs)

Movie ratings were obtained from the Official [GroupLens Website](https://grouplens.org/datasets/movielens/latest/)

<br>

<H2 style="text-align: left; color:black;">References</h2>

<br>
F. Maxwell Harper and Joseph A. Konstan. 2015. The MovieLens Datasets: History and Context. ACM Transactions on Interactive Intelligent Systems (TiiS) 5, 4: 19:1–19:19. https://doi.org/10.1145/2827872


<br><br>

<H1 style="text-align: center; color:black;"> 1. Data Cleaning </h1>

<H2 style="text-align: center; color:black;"> Exploring, cleaning and saving the dataset into a new file.</h2>
<br><br>

In [1]:
## Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

pd.options.display.max_columns = 30

In [2]:
###### 
df = pd.read_csv("/Users/luis/Documents/Proyects_To_Export/0261_DS_Projects/venv_0261_DS_Projects_311/Projects/0261_Project_01/0261_Project_01_Data/movies_metadata.csv", low_memory=False)

#df = pd.read_csv("/xx/xx/Desktop/movies_metadata.csv", low_memory=False)




In [3]:
df.head(3)


adult                              belongs_to_collection    budget   
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000  \
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   

                                              genres   
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  \
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   

                               homepage     id    imdb_id original_language   
0  http://toystory.disney.com/toy-story    862  tt0114709                en  \
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   

     original_title                                           overview   
0         Toy Story  Led by Woody, Andy's toys live happily in his ...  \
1           Jumanji  When siblings Judy and Peter discover an encha...   
2  Grumpier Old Men  A family wedding reignites the ancient feud be...   

  popularity                       poster_path   
0  21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  \
1  17.015539  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   
2    11.7129  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg   

                                production_companies   
0     [{'name': 'Pixar Animation Studios', 'id': 3}]  \
1  [{'name': 'TriStar Pictures', 'id': 559}, {'na...   
2  [{'name': 'Warner Bros.', 'id': 6194}, {'name'...   

                                production_countries release_date   
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30  \
1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15   
2  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   

       revenue  runtime                                   spoken_languages   
0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]  \
1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline   
0  Released                                                NaN  \
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   

              title  video  vote_average  vote_count  
0         Toy Story  False           7.7      5415.0  
1           Jumanji  False           6.9      2413.0  
2  Grumpier Old Men  False           6.5        92.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

In [5]:
df.isna().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

### Inspect Nested Columns


In [6]:
#df['belongs_to_collection'][0]
#"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"

#df['genres'][0]
#"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"


#df['production_companies'][0]
#"[{'name': 'Pixar Animation Studios', 'id': 3}]"


#df['production_countries'][0]
#"[{'iso_3166_1': 'US', 'name': 'United States of America'}]"


df['spoken_languages'][0]
#"[{'iso_639_1': 'en', 'name': 'English'}]"


"[{'iso_639_1': 'en', 'name': 'English'}]"

### Drop Columns That Are Not Relevant For Further Exploration and Analysis


In [7]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [8]:
for i, w in enumerate(df.columns):
    #print(i)
    #print(w)
    print("\n")
    print(f"Column Name: {w}")
    print(df[w].value_counts())



Column Name: adult
adult
False                                                                                                                             45454
True                                                                                                                                  9
 - Written by Ørnås                                                                                                                   1
 Rune Balot goes to a casino connected to the October corporation to try to wrap up her case once and for all.                        1
 Avalanche Sharks tells the story of a bikini contest that turns into a horrifying affair when it is hit by a shark avalanche.        1
Name: count, dtype: int64


Column Name: belongs_to_collection
belongs_to_collection
{'id': 415931, 'name': 'The Bowery Boys', 'poster_path': '/q6sA4bzMT9cK7EEmXYwt7PNrL5h.jpg', 'backdrop_path': '/foe3kuiJmg5AklhtD3skWbaTMf2.jpg'}                 29
{'id': 421566, 'name': 'Totò Collection', '

In [9]:
df.drop(columns=['adult','homepage','imdb_id',  'original_title', 'video'], inplace=True)


In [10]:
df.columns

Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [11]:
df.head(2)

belongs_to_collection    budget   
0  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000  \
1                                                NaN  65000000   

                                              genres    id original_language   
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   862                en  \
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  8844                en   

                                            overview popularity   
0  Led by Woody, Andy's toys live happily in his ...  21.946943  \
1  When siblings Judy and Peter discover an encha...  17.015539   

                        poster_path   
0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  \
1  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   

                                production_companies   
0     [{'name': 'Pixar Animation Studios', 'id': 3}]  \
1  [{'name': 'TriStar Pictures', 'id': 559}, {'na...   

                                production_countries release_date   
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30  \
1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15   

       revenue  runtime                                   spoken_languages   
0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]  \
1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   

     status                                    tagline      title   
0  Released                                        NaN  Toy Story  \
1  Released  Roll the dice and unleash the excitement!    Jumanji   

   vote_average  vote_count  
0           7.7      5415.0  
1           6.9      2413.0

## Handling Stringified JSON Files

In [12]:
### ast.literal_eval
import json
import ast


In [13]:
json_col = ['belongs_to_collection', 'genres', 'production_companies', 'production_countries', 'spoken_languages']


In [14]:
json_col

['belongs_to_collection',
 'genres',
 'production_companies',
 'production_countries',
 'spoken_languages']

##### Column: belongs_to_collection

In [15]:

df['belongs_to_collection'][0]
##"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"


"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"

In [16]:
### Cannot use ast.literal_eval on "belongs_to_collection"
#df['belongs_to_collection'].apply(ast.literal_eval)[0]
##ValueError: malformed node or string: nan

## need to verify which are the 0's, missing values, datatypes, etc

In [17]:
df['belongs_to_collection'].info()## dtype object
df['belongs_to_collection'].isna().sum()## 40972 missing values


<class 'pandas.core.series.Series'>
RangeIndex: 45466 entries, 0 to 45465
Series name: belongs_to_collection
Non-Null Count  Dtype 
--------------  ----- 
4494 non-null   object
dtypes: object(1)
memory usage: 355.3+ KB


40972

In [18]:
## Verifying index 3
#df['belongs_to_collection'][3]## nan

## Verifying index 2
df['belongs_to_collection'][2]


"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}"

df['belongs_to_collection'].info()## dtype object
df['belongs_to_collection'].isna().sum()## 40972 missing values

* Cannot use ast.literal_eval at the moment
df['belongs_to_collection'].apply(ast.literal_eval)[0]
ValueError: malformed node or string: nan

ast.literal_eval raises errors if passing objects other than strings
- Inspect and modify df['belongs_to_collection']
- Can build a function and use "isinstance()"


In [19]:
## Using and applying a function with isinstance

### Error: TypeError: isinstance() takes no keyword arguments
#df["belongs_to_collection"].apply(lambda x: isinstance(obj=x, class_or_tuple=str))

df["belongs_to_collection"].apply(lambda x: isinstance(x,str))
### Will apply ast.literal to only the strings


0         True
1        False
2         True
3        False
4         True
         ...  
45461    False
45462    False
45463    False
45464    False
45465    False
Name: belongs_to_collection, Length: 45466, dtype: bool

In [20]:
###### Apply ast.literal_eval to only the strings

df["belongs_to_collection"] = df["belongs_to_collection"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)


In [21]:
df["belongs_to_collection"].head()

df["belongs_to_collection"][0]

{'id': 10194,
 'name': 'Toy Story Collection',
 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg',
 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}

##### Column: production_companies


In [22]:
df["production_companies"]

0           [{'name': 'Pixar Animation Studios', 'id': 3}]
1        [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2        [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3        [{'name': 'Twentieth Century Fox Film Corporat...
4        [{'name': 'Sandollar Productions', 'id': 5842}...
                               ...                        
45461                                                   []
45462               [{'name': 'Sine Olivia', 'id': 19653}]
45463    [{'name': 'American World Pictures', 'id': 6165}]
45464                 [{'name': 'Yermoliev', 'id': 88753}]
45465                                                   []
Name: production_companies, Length: 45466, dtype: object

df["production_companies"]

0           [{'name': 'Pixar Animation Studios', 'id': 3}]
1        [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2        [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3        [{'name': 'Twentieth Century Fox Film Corporat...
4        [{'name': 'Sandollar Productions', 'id': 5842}...
                               ...                        
45461                                                   []
45462               [{'name': 'Sine Olivia', 'id': 19653}]
45463    [{'name': 'American World Pictures', 'id': 6165}]
45464                 [{'name': 'Yermoliev', 'id': 88753}]
45465                                                   []
Name: production_companies, Length: 45466, dtype: object


In [23]:
## Error: ValueError: malformed node or string: nan
#df["production_companies"].apply(lambda x: ast.literal_eval(x))

df["production_companies"] = df["production_companies"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)


In [24]:
df["production_companies"][4]

[{'name': 'Sandollar Productions', 'id': 5842},
 {'name': 'Touchstone Pictures', 'id': 9195}]

##### Column: production_countries

In [25]:
df["production_countries"][6]
##"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]"

"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]"

Strings before the list
"[]"

"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]"

In [26]:

df["production_countries"] = df["production_countries"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)



In [27]:
df["production_countries"][6]
##[{'iso_3166_1': 'DE', 'name': 'Germany'},
## {'iso_3166_1': 'US', 'name': 'United States of America'}]

[{'iso_3166_1': 'DE', 'name': 'Germany'},
 {'iso_3166_1': 'US', 'name': 'United States of America'}]

##### Column: spoken_languages

In [28]:
df["spoken_languages"][5]

"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'es', 'name': 'Español'}]"

In [29]:

df["spoken_languages"] = df["spoken_languages"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)


In [30]:
df["spoken_languages"][5]

[{'iso_639_1': 'en', 'name': 'English'},
 {'iso_639_1': 'es', 'name': 'Español'}]

##### Column: genres

In [31]:
df['genres'][0]
## "[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [32]:
### A)
#df["genres"].apply(lambda x: json.loads(x.replace("'", '"')))#[0]

### B)
df['genres'].apply(ast.literal_eval)[0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [33]:
df['genres'] = df['genres'].apply(ast.literal_eval)

In [34]:
#df["genres"].info()
df["genres"]
df.head(2)

belongs_to_collection    budget   
0  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000  \
1                                                NaN  65000000   

                                              genres    id original_language   
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   862                en  \
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  8844                en   

                                            overview popularity   
0  Led by Woody, Andy's toys live happily in his ...  21.946943  \
1  When siblings Judy and Peter discover an encha...  17.015539   

                        poster_path   
0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  \
1  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   

                                production_companies   
0     [{'name': 'Pixar Animation Studios', 'id': 3}]  \
1  [{'name': 'TriStar Pictures', 'id': 559}, {'na...   

                                production_countries release_date   
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30  \
1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15   

       revenue  runtime                                   spoken_languages   
0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]  \
1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   

     status                                    tagline      title   
0  Released                                        NaN  Toy Story  \
1  Released  Roll the dice and unleash the excitement!    Jumanji   

   vote_average  vote_count  
0           7.7      5415.0  
1           6.9      2413.0

## Flatten Nested Columns

df["belongs_to_collection"][0]
{'id': 10194,
 'name': 'Toy Story Collection',
 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg',
 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}
 
Dictionary, 4 key-value pairs
Only want the name of the collection
function:
apply the function to each element that belongs_to_collection column


In [35]:
###### 
df["belongs_to_collection"] = df["belongs_to_collection"].apply(lambda x: x['name'] if isinstance(x, dict) else np.nan)


In [36]:
###### 40975 missing values
###### 
df["belongs_to_collection"].value_counts(dropna = False).head(20)


belongs_to_collection
NaN                                       40975
The Bowery Boys                              29
Totò Collection                              27
James Bond Collection                        26
Zatôichi: The Blind Swordsman                26
The Carry On Collection                      25
Pokémon Collection                           22
Charlie Chan (Sidney Toler) Collection       21
Godzilla (Showa) Collection                  16
Uuno Turhapuro                               15
Dragon Ball Z (Movie) Collection             15
Charlie Chan (Warner Oland) Collection       15
The Land Before Time Collection              14
Monster High Collection                      14
Sharpe Collection                            13
George Carlin Comedy Collection              13
Johan Falk GSI Collection                    12
Sherlock Holmes (1939 series)                12
Friday the 13th Collection                   12
The Amityville Horror Collection             12
Name: count, dtype

In [37]:
##df["production_companies"].value_counts()
df["production_companies"][4]
## 

[{'name': 'Sandollar Productions', 'id': 5842},
 {'name': 'Touchstone Pictures', 'id': 9195}]

df["production_companies"][4]
[{'name': 'Sandollar Productions', 'id': 5842},
 {'name': 'Touchstone Pictures', 'id': 9195}]


In [38]:

df["production_companies"] = df["production_companies"].apply(lambda x: "|".join(i["name"] for i in x) if isinstance(x, list) else np.nan)


In [39]:
df["production_companies"]

0                                  Pixar Animation Studios
1        TriStar Pictures|Teitler Film|Interscope Commu...
2                              Warner Bros.|Lancaster Gate
3                   Twentieth Century Fox Film Corporation
4                Sandollar Productions|Touchstone Pictures
                               ...                        
45461                                                     
45462                                          Sine Olivia
45463                              American World Pictures
45464                                            Yermoliev
45465                                                     
Name: production_companies, Length: 45466, dtype: object

In [40]:
## Value counts
df["production_companies"].value_counts(dropna=False).head(20)

### 11875 empty values
### Replace empty string with nan

production_companies
                                          11875
Metro-Goldwyn-Mayer (MGM)                   742
Warner Bros.                                540
Paramount Pictures                          505
Twentieth Century Fox Film Corporation      439
Universal Pictures                          320
RKO Radio Pictures                          247
Columbia Pictures Corporation               207
Columbia Pictures                           146
Mosfilm                                     145
Walt Disney Pictures                         85
Universal International Pictures (UI)        82
New Line Cinema                              75
Walt Disney Productions                      75
Shaw Brothers                                71
Touchstone Pictures                          70
Toho Company                                 65
TriStar Pictures                             62
Orion Pictures                               61
Hammer Film Productions                      60
Name: count, dtype:

In [41]:
### Replace empty string with nan
df["production_companies"].replace("", np.nan, inplace=True)

In [42]:
## Value counts
df["production_companies"].value_counts(dropna=False).head(20)


production_companies
NaN                                       11881
Metro-Goldwyn-Mayer (MGM)                   742
Warner Bros.                                540
Paramount Pictures                          505
Twentieth Century Fox Film Corporation      439
Universal Pictures                          320
RKO Radio Pictures                          247
Columbia Pictures Corporation               207
Columbia Pictures                           146
Mosfilm                                     145
Walt Disney Pictures                         85
Universal International Pictures (UI)        82
Walt Disney Productions                      75
New Line Cinema                              75
Shaw Brothers                                71
Touchstone Pictures                          70
Toho Company                                 65
TriStar Pictures                             62
Orion Pictures                               61
Hammer Film Productions                      60
Name: count, dtype:

In [43]:
df["production_countries"]

0        [{'iso_3166_1': 'US', 'name': 'United States o...
1        [{'iso_3166_1': 'US', 'name': 'United States o...
2        [{'iso_3166_1': 'US', 'name': 'United States o...
3        [{'iso_3166_1': 'US', 'name': 'United States o...
4        [{'iso_3166_1': 'US', 'name': 'United States o...
                               ...                        
45461               [{'iso_3166_1': 'IR', 'name': 'Iran'}]
45462        [{'iso_3166_1': 'PH', 'name': 'Philippines'}]
45463    [{'iso_3166_1': 'US', 'name': 'United States o...
45464             [{'iso_3166_1': 'RU', 'name': 'Russia'}]
45465     [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]
Name: production_countries, Length: 45466, dtype: object

In [44]:
df["production_countries"][15]


[{'iso_3166_1': 'FR', 'name': 'France'},
 {'iso_3166_1': 'US', 'name': 'United States of America'}]

df["production_countries"][6]
[{'iso_3166_1': 'DE', 'name': 'Germany'},
 {'iso_3166_1': 'US', 'name': 'United States of America'}]

df["production_countries"]


In [45]:

df["production_countries"] = df["production_countries"].apply(lambda x: "|".join(i["name"] for i in x) if isinstance(x, list) else np.nan)



In [46]:
df["production_countries"][15]


'France|United States of America'

In [47]:
#df["production_countries"].value_counts(dropna=False)
### empty string has 6282 values
### Replacing empty string with missing values

In [48]:

df["production_countries"].replace("", np.nan, inplace=True)

In [49]:
df["production_countries"].value_counts().head(20)
df["production_countries"].value_counts(dropna=False).head(10)
### empty string has 6282 values
### Replacing empty string with missing values

production_countries
United States of America    17851
NaN                          6288
United Kingdom               2238
France                       1654
Japan                        1356
Italy                        1030
Canada                        840
Germany                       749
India                         735
Russia                        735
Name: count, dtype: int64

In [50]:
df["spoken_languages"]

0                 [{'iso_639_1': 'en', 'name': 'English'}]
1        [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2                 [{'iso_639_1': 'en', 'name': 'English'}]
3                 [{'iso_639_1': 'en', 'name': 'English'}]
4                 [{'iso_639_1': 'en', 'name': 'English'}]
                               ...                        
45461               [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462                    [{'iso_639_1': 'tl', 'name': ''}]
45463             [{'iso_639_1': 'en', 'name': 'English'}]
45464                                                   []
45465             [{'iso_639_1': 'en', 'name': 'English'}]
Name: spoken_languages, Length: 45466, dtype: object

df["spoken_languages"][5]
[{'iso_639_1': 'en', 'name': 'English'},
 {'iso_639_1': 'es', 'name': 'Español'}]


In [51]:

df["spoken_languages"] = df["spoken_languages"].apply(lambda x: "|".join(i["name"] for i in x) if isinstance(x, list) else np.nan)


In [52]:
df["spoken_languages"].value_counts(dropna=False).head(20)
## empty string 3952

spoken_languages
English             22395
                     3952
Français             1853
日本語                  1289
Italiano             1218
Español               902
Pусский               807
Deutsch               762
English|Français      681
English|Español       572
हिन्दी                481
English|Deutsch       462
한국어/조선말               425
普通话                   347
English|Italiano      326
svenska               311
No Language           303
suomi                 275
Português             275
Polski                213
Name: count, dtype: int64

In [53]:

df["spoken_languages"].replace("", np.nan, inplace=True)

In [54]:
df["spoken_languages"].value_counts(dropna=False).head(20)


spoken_languages
English             22395
NaN                  3958
Français             1853
日本語                  1289
Italiano             1218
Español               902
Pусский               807
Deutsch               762
English|Français      681
English|Español       572
हिन्दी                481
English|Deutsch       462
한국어/조선말               425
普通话                   347
English|Italiano      326
svenska               311
No Language           303
Português             275
suomi                 275
Polski                213
Name: count, dtype: int64

In [55]:
df['genres']

0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                           [{'id': 35, 'name': 'Comedy'}]
                               ...                        
45461    [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                        [{'id': 18, 'name': 'Drama'}]
45463    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                   []
45465                                                   []
Name: genres, Length: 45466, dtype: object

df['genres'][0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]


In [56]:
df["genres"].value_counts(dropna=False).head(10)

genres
[{'id': 18, 'name': 'Drama'}]                                                                    5000
[{'id': 35, 'name': 'Comedy'}]                                                                   3621
[{'id': 99, 'name': 'Documentary'}]                                                              2723
[]                                                                                               2442
[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]                                  1301
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]                                      1135
[{'id': 27, 'name': 'Horror'}]                                                                    974
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]                                  930
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]     593
[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name': 'Comedy'}]                

In [57]:
df['genres'] = df['genres'].apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

#df["genres"] = df["genres"].apply(lambda x: "|".join(i["name"] for i in x))

In [58]:
df["genres"].value_counts(dropna=False).head(10)

## Empty string 2442

genres
Drama                   5000
Comedy                  3621
Documentary             2723
                        2442
Drama|Romance           1301
Comedy|Drama            1135
Horror                   974
Comedy|Romance           930
Comedy|Drama|Romance     593
Drama|Comedy             532
Name: count, dtype: int64

In [59]:
## Replacing empty string with NaN
df["genres"].replace("", np.nan, inplace=True)

In [60]:
df["genres"].value_counts(dropna=False).head(10)

genres
Drama                   5000
Comedy                  3621
Documentary             2723
NaN                     2442
Drama|Romance           1301
Comedy|Drama            1135
Horror                   974
Comedy|Romance           930
Comedy|Drama|Romance     593
Drama|Comedy             532
Name: count, dtype: int64

### Modified DF vs initial DF Comparison

##### Initial DF

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64


##### Modified DF
-- Dropped columns
-- Stringified JSON
-- Preprocessed some columns
-- Changed from empty strings into missing values

df.isna().sum()

belongs_to_collection    40975
budget                       0
genres                    2442
id                           0
original_language           11
overview                   954
popularity                   5
poster_path                386
production_companies     11881
production_countries      6288
release_date                87
revenue                      6
runtime                    263
spoken_languages          3958
status                      87
tagline                  25054
title                        6
vote_average                 6
vote_count                   6
dtype: int64


## Cleaning Numerical Columns

#### Numerical columns: ["budget","popularity", "revenue", "runtime", "vote_average", "vote_count"]

In [61]:
###### 
###### Getting Error trying to change
###### ValueError: could not convert string to float: '/ff9qCepilowshEtG2GYWwzt2bs4.jpg'
###### This means there is still unclean data and mixed datatypes

df["budget"].astype("float")


ValueError: could not convert string to float: '/ff9qCepilowshEtG2GYWwzt2bs4.jpg'

In [62]:
## Error
#df["budget"].astype(dtype='float')
###ValueError: could not convert string to float: '/ff9qCepilowshEtG2GYWwzt2bs4.jpg'

###### dframe[dframe['Last Name'].str.contains('Turner')]
df[df["budget"] == '/ff9qCepilowshEtG2GYWwzt2bs4.jpg']



belongs_to_collection                            budget   
19730                   NaN  /ff9qCepilowshEtG2GYWwzt2bs4.jpg  \

                                                  genres          id   
19730  Carousel Productions|Vision View Entertainment...  1997-08-20  \

      original_language  overview popularity   poster_path   
19730             104.0  Released        NaN  Midnight Man  \

      production_companies production_countries release_date  revenue   
19730                  NaN                  NaN            1      NaN  \

       runtime spoken_languages status tagline title  vote_average  vote_count  
19730      NaN              NaN    NaN     NaN   NaN           NaN         NaN

In [63]:
###### Can pass the budget to pd.to_numeric
###### 
#pd.to_numeric(df["budget"])

###### using errors = "coerce"
###### "ignore", "raise" or "coerce"
##### coerce - All invalid elements will be set to NaN

###### This works
#pd.to_numeric(df["budget"], errors="coerce")
df["budget"] = pd.to_numeric(df["budget"], errors="coerce")


In [64]:
df["budget"].info()##float64


<class 'pandas.core.series.Series'>
RangeIndex: 45466 entries, 0 to 45465
Series name: budget
Non-Null Count  Dtype  
--------------  -----  
45463 non-null  float64
dtypes: float64(1)
memory usage: 355.3 KB


In [65]:
###### 

df["budget"].isna().sum()#### Result: 3 missing values

df["budget"].value_counts(dropna=False)
#### 0 is the most frequent value


#df["budget"].describe()
####count    4.546300e+04
####mean     4.224579e+06
####std      1.742413e+07
####min      0.000000e+00
####25%      0.000000e+00
####50%      0.000000e+00
####75%      0.000000e+00
####max      3.800000e+08
#Name: budget, dtype: float64


#### Over 75% of the movies have a budget of 0.
#### Can infer that the value 0 was a placeholder for a missing value
##### Assumption: When people do not know the budget of a movie they put 0 in it


budget
0.0           36573
5000000.0       286
10000000.0      259
20000000.0      243
2000000.0       242
              ...  
9750000.0         1
7275000.0         1
78146652.0        1
280.0             1
1254040.0         1
Name: count, Length: 1224, dtype: int64

In [66]:
###### Replacing the budget value of 0 with NaN
df["budget"] = df["budget"].replace(to_replace=0, value=np.nan)



In [67]:
df["budget"].value_counts(dropna=False)

budget
NaN            36576
5000000.0        286
10000000.0       259
20000000.0       243
2000000.0        242
               ...  
270000000.0        1
923.0              1
72500000.0         1
2160000.0          1
1254040.0          1
Name: count, Length: 1223, dtype: int64

In [68]:
### Changing budget units to millions in currency
df["budget"] = df["budget"].div(1000000)


In [69]:
df["budget"].value_counts(dropna=False)

budget
NaN           36576
5.000000        286
10.000000       259
20.000000       243
2.000000        242
              ...  
270.000000        1
0.000923          1
72.500000         1
2.160000          1
1.254040          1
Name: count, Length: 1223, dtype: int64

In [70]:
df.info()
#### budget has the appropriate dtype float
#### budget column converted with missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   belongs_to_collection  4491 non-null   object 
 1   budget                 8890 non-null   float64
 2   genres                 43024 non-null  object 
 3   id                     45466 non-null  object 
 4   original_language      45455 non-null  object 
 5   overview               44512 non-null  object 
 6   popularity             45461 non-null  object 
 7   poster_path            45080 non-null  object 
 8   production_companies   33585 non-null  object 
 9   production_countries   39178 non-null  object 
 10  release_date           45379 non-null  object 
 11  revenue                45460 non-null  float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object 
 14  status                 45379 non-null  object 
 15  ta

In [71]:
###### "revenue"
######  11  revenue                45460 non-null  float64
df["revenue"].value_counts(dropna=False)

###### The majority of films have a revenue of 0 which means there are missing values as well
###### Note: 0 could be a placeholder for a missing value
##### Assumption: 0 is a placeholder for a missing value

revenue
0.0           38052
12000000.0       20
10000000.0       19
11000000.0       19
2000000.0        18
              ...  
36565280.0        1
439564.0          1
35610100.0        1
10217873.0        1
1413000.0         1
Name: count, Length: 6864, dtype: int64

In [72]:
### Changing revenue units to millions in currency (Assumption: USD)

df["revenue"] = df["revenue"].replace(to_replace=0, value=np.nan)
df["revenue"] = df["revenue"].div(1000000)

In [73]:
df["revenue"].value_counts(dropna=False)

revenue
NaN          38058
12.000000       20
11.000000       19
10.000000       19
2.000000        18
             ...  
36.565280        1
0.439564         1
35.610100        1
10.217873        1
1.413000         1
Name: count, Length: 6863, dtype: int64

In [74]:
### Changed units to budget and revenue
### Changing column names for both of them

df.rename(columns = {"budget":"budget_musd", "revenue":"revenue_musd"}, inplace=True)

In [75]:
df.columns

Index(['belongs_to_collection', 'budget_musd', 'genres', 'id',
       'original_language', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue_musd', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title', 'vote_average', 'vote_count'],
      dtype='object')

* Numerical columns: ["budget","id", "popularity", "revenue", "runtime", "vote_average", "vote_count"]

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   belongs_to_collection  4491 non-null   object 
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object 
 3   id                     45466 non-null  object 
 4   original_language      45455 non-null  object 
 5   overview               44512 non-null  object 
 6   popularity             45461 non-null  object 
 7   poster_path            45080 non-null  object 
 8   production_companies   33585 non-null  object 
 9   production_countries   39178 non-null  object 
 10  release_date           45379 non-null  object 
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object 
 14  status                 45379 non-null  object 
 15  ta

In [77]:
###### 
df["runtime"] = df["runtime"].replace(to_replace=0, value=np.nan)


In [78]:
df["id"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 45466 entries, 0 to 45465
Series name: id
Non-Null Count  Dtype 
--------------  ----- 
45466 non-null  object
dtypes: object(1)
memory usage: 355.3+ KB


In [79]:
pd.to_numeric(df["id"], errors="coerce")

0           862.0
1          8844.0
2         15602.0
3         31357.0
4         11862.0
           ...   
45461    439050.0
45462    111109.0
45463     67758.0
45464    227506.0
45465    461257.0
Name: id, Length: 45466, dtype: float64

In [80]:
df["id"].value_counts(dropna=False).head(20)
###### Every id should be unique. There should not be any duplicates and there are duplicates
###### Will handle missing values and duplicate values later


id
141971    3
168538    2
25541     2
15028     2
11115     2
84198     2
13209     2
77221     2
152795    2
12600     2
10991     2
42495     2
14788     2
18440     2
105045    2
159849    2
22649     2
4912      2
132641    2
110428    2
Name: count, dtype: int64

### Confirming duplicate values
### Note: takes a long time
numbers = df["id"].to_list()

duplicates = [number for number in numbers if numbers.count(number) > 1]
unique_duplicates = list(set(duplicates))

print(unique_duplicates)

# Returns: [2, 3, 5]


In [81]:
###### 
#pd.to_numeric(df["popularity"])
######  Error: ValueError: Unable to parse string "Beware Of Frost Bites" at position 35587

df["popularity"] = pd.to_numeric(df["popularity"], errors="coerce")
# Will create a missing value where the error of "Beware Of Frost Bites" is


In [82]:
##
df["popularity"].value_counts(dropna=False)

###### The value 0 appears 66 times
###### Having films with 0 popularity could be possible


popularity
0.000000    66
0.000001    56
0.000308    43
0.000220    40
0.000844    38
            ..
4.762242     1
6.173752     1
0.645652     1
0.556292     1
0.163015     1
Name: count, Length: 43758, dtype: int64

In [83]:
df["vote_average"].value_counts(dropna=False)
###### There are 0 votes for almost 3000 films [2998] This could be possible.
###### Even if the rating is between 1 and 10


vote_average
0.0    2998
6.0    2468
5.0    2001
7.0    1886
6.5    1722
       ... 
9.4       3
9.6       1
9.8       1
0.7       1
1.1       1
Name: count, Length: 93, dtype: int64

In [84]:
###### Want all the rows with the vote_average == 0 in the columns vote_average
df.loc[df["vote_average"] == 0, "vote_average"]

83       0.0
107      0.0
126      0.0
132      0.0
137      0.0
        ... 
45432    0.0
45434    0.0
45452    0.0
45464    0.0
45465    0.0
Name: vote_average, Length: 2998, dtype: float64

In [85]:
###### Finding the rows on the column vote_average where vote count is 0
df.loc[df["vote_count"] == 0, "vote_average"]

83       0.0
107      0.0
126      0.0
132      0.0
137      0.0
        ... 
45432    0.0
45434    0.0
45452    0.0
45464    0.0
45465    0.0
Name: vote_average, Length: 2899, dtype: float64

In [86]:
###### Changing these 0 values to missing values
###### Assumption: For movies that they do not have any rating, the average rating is automatically 0
###### Finding the rows on the column vote_average where vote count is 0

#df.loc[df["vote_count"] == 0, "vote_average"]

df.loc[df["vote_count"] == 0, "vote_average"] = np.nan


In [87]:
###### Finding the rows on the column vote_average where vote count is 0
df.loc[df["vote_count"] == 0, "vote_average"]

83      NaN
107     NaN
126     NaN
132     NaN
137     NaN
         ..
45432   NaN
45434   NaN
45452   NaN
45464   NaN
45465   NaN
Name: vote_average, Length: 2899, dtype: float64

In [88]:
df.head(1)

belongs_to_collection  budget_musd                   genres   id   
0  Toy Story Collection         30.0  Animation|Comedy|Family  862  \

  original_language                                           overview   
0                en  Led by Woody, Andy's toys live happily in his ...  \

   popularity                       poster_path     production_companies   
0   21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  Pixar Animation Studios  \

       production_countries release_date  revenue_musd  runtime   
0  United States of America   1995-10-30    373.554033     81.0  \

  spoken_languages    status tagline      title  vote_average  vote_count  
0          English  Released     NaN  Toy Story           7.7      5415.0

In [89]:
df["vote_average"].value_counts(dropna=False)

vote_average
NaN    2905
6.0    2468
5.0    2001
7.0    1886
6.5    1722
       ... 
9.4       3
9.6       1
9.8       1
0.7       1
1.1       1
Name: count, Length: 93, dtype: int64

## Cleaning DateTime Format Columns

DateTime cols = ["release_date"]

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   belongs_to_collection  4491 non-null   object 
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object 
 3   id                     45466 non-null  object 
 4   original_language      45455 non-null  object 
 5   overview               44512 non-null  object 
 6   popularity             45460 non-null  float64
 7   poster_path            45080 non-null  object 
 8   production_companies   33585 non-null  object 
 9   production_countries   39178 non-null  object 
 10  release_date           45379 non-null  object 
 11  revenue_musd           7408 non-null   float64
 12  runtime                43645 non-null  float64
 13  spoken_languages       41508 non-null  object 
 14  status                 45379 non-null  object 
 15  ta

In [91]:
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")

* 10  release_date           45376 non-null  datetime64[ns]

df.info()


In [92]:
df["release_date"].isna().sum()### 90

90

In [93]:
df["release_date"].value_counts(dropna=False)
### 1st of Jan is a very frequent date
### Assumption: This could be a placeholder for films where the release date is not known
### Where the year is the only known information


release_date
2008-01-01    136
2009-01-01    121
2007-01-01    118
2005-01-01    111
2006-01-01    101
             ... 
1957-09-26      1
1938-11-21      1
1936-08-19      1
2010-01-27      1
1917-10-21      1
Name: count, Length: 17334, dtype: int64

In [94]:
### 
df.head(2)

belongs_to_collection  budget_musd                    genres    id   
0  Toy Story Collection         30.0   Animation|Comedy|Family   862  \
1                   NaN         65.0  Adventure|Fantasy|Family  8844   

  original_language                                           overview   
0                en  Led by Woody, Andy's toys live happily in his ...  \
1                en  When siblings Judy and Peter discover an encha...   

   popularity                       poster_path   
0   21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  \
1   17.015539  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   

                                production_companies   
0                            Pixar Animation Studios  \
1  TriStar Pictures|Teitler Film|Interscope Commu...   

       production_countries release_date  revenue_musd  runtime   
0  United States of America   1995-10-30    373.554033     81.0  \
1  United States of America   1995-12-15    262.797249    104.0   

   spoken_languages    status                                    tagline   
0           English  Released                                        NaN  \
1  English|Français  Released  Roll the dice and unleash the excitement!   

       title  vote_average  vote_count  
0  Toy Story           7.7      5415.0  
1    Jumanji           6.9      2413.0

## Clean String Text Columns

string columns = ['belongs_to_collection','genres','original_language', 
                'overview', 'poster_path','production_companies',
                'production_countries', 'spoken_languages', 'status',
                'tagline','title']

In [95]:
df["original_language"].value_counts(dropna=False).head(50)
##NaN       11
### Missing values but they are indicated as so


original_language
en     32269
fr      2438
it      1529
ja      1350
de      1080
es       994
ru       826
hi       508
ko       444
zh       409
sv       384
pt       316
cn       313
fi       297
nl       248
da       225
pl       219
tr       150
cs       130
el       113
no       106
fa       101
hu       100
ta        78
th        76
he        67
sr        63
ro        57
te        45
ar        39
ml        36
xx        33
bn        29
hr        29
mr        25
is        24
et        24
tl        23
id        20
lv        18
ka        18
sl        17
uk        16
bs        14
ca        12
NaN       11
bg        10
ab        10
vi        10
sk         9
Name: count, dtype: int64

##### overview

In [96]:

df["overview"].value_counts(dropna=False).head(10)
### There are some rows where there is no overview
### There are different strings with the same meaning

#overview
#NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               954
#No overview found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                133
#No Overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5
#No movie overview available.



overview
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               954
No overview found.                                                                                                                                                                                                                                                                                                                                                                                                       

In [97]:
###### Search for specific strings
###### Quantity of strings with same information

###### dframe[dframe['Last Name'].str.contains('Turner')]
#df[df["budget"] == '/ff9qCepilowshEtG2GYWwzt2bs4.jpg']

#df[df["overview"].str.contains('overview')]
#print(len(df[(df["overview"].str.contains('Overview') == True) | (df["overview"].str.contains('overview') == True)]))

######There are 162 rows that contain either Overview or overview

#df[(df["overview"].str.contains('Overview') == True) | (df["overview"].str.contains('overview') == True)]

print(len(df[(df["overview"].str.contains('No Overview') == True)]))
### 7

###### No Overview
print(len(df[(df["overview"].str.contains('No overview') == True)]))
### 138

###### No overview found.
print(len(df[(df["overview"].str.contains('No overview found.') == True)]))
### 133

###### No movie overview available.
print(len(df[(df["overview"].str.contains('No movie overview available') == True)]))
### 4

###### No movie overview available. with an extra space at the end
print(len(df[(df["overview"].str.contains('No movie overview available. ') == True)]))
### 4

###### No overview yet. 
print(len(df[(df["overview"].str.contains('No overview yet') == True)]))
### 2


print(len(df[df["overview"] == '']))
### 0

print(len(df[df["overview"] == ' ']))
### 5 #It is a white space



7
138
133
4
1
2
0
5


In [98]:
### Replacing Strings with missing values - specific str

df["overview"].replace(to_replace="No overview found.", value=np.nan, inplace=True)
df["overview"].replace(to_replace="No Overview", value=np.nan, inplace=True)
df["overview"].replace(to_replace="No movie overview available.", value=np.nan, inplace=True)
df["overview"].replace(to_replace=" ", value=np.nan, inplace=True)
df["overview"].replace(to_replace="No overview yet.", value=np.nan, inplace=True)




In [99]:
###### 
###### dframe[dframe['Last Name'].str.contains('Turner')]
#df[df["budget"] == '/ff9qCepilowshEtG2GYWwzt2bs4.jpg']

#df[df["overview"].str.contains('overview')]
#print(len(df[(df["overview"].str.contains('Overview') == True) | (df["overview"].str.contains('overview') == True)]))

######There are 162 rows that contain either Overview or overview

#df[(df["overview"].str.contains('Overview') == True) | (df["overview"].str.contains('overview') == True)]

print(len(df[(df["overview"].str.contains('No Overview') == True)]))
### 7
### 0

###### No Overview
print(len(df[(df["overview"].str.contains('No overview') == True)]))
### 138
### 3

###### No overview found.
print(len(df[(df["overview"].str.contains('No overview found.') == True)]))
### 133
### 0

###### No movie overview available.
print(len(df[(df["overview"].str.contains('No movie overview available') == True)]))
### 4
### 1

###### No movie overview available. with an extra space at the end
print(len(df[(df["overview"].str.contains('No movie overview available. ') == True)]))
### 4
### 1

###### No overview yet. 
print(len(df[(df["overview"].str.contains('No overview yet') == True)]))
### 2
### 0


print(len(df[df["overview"] == '']))
### 0
### 0

print(len(df[df["overview"] == ' ']))
### 5 #It is a white space
### 0



0
3
0
1
1
0
0
0


In [100]:
###### No Overview

print(len(df[(df["overview"].str.contains('No overview') == True)]))
### 138
### 3
###### No movie overview available.

print(len(df[(df["overview"].str.contains('No movie overview available') == True)]))
### 4
### 1
###### No movie overview available. with an extra space at the end

print(len(df[(df["overview"].str.contains('No movie overview available. ') == True)]))
### 4
### 1

3
1
1


In [101]:
### Note: There are still these 3 rows with no overview in them
df[(df["overview"].str.contains('No overview') == True)]


belongs_to_collection  budget_musd       genres      id   
30352                   NaN          NaN  Documentary   87851  \
31596                   NaN          NaN          NaN   58400   
42398                   NaN          NaN          NaN  358293   

      original_language           overview  popularity   
30352                en  No overview found    0.004707  \
31596                it        No overview    1.597821   
42398                en       No overview.    0.001180   

                            poster_path production_companies   
30352                               NaN                  NaN  \
31596  /irGylTvNJESdEc2UiI5KGLEzA9L.jpg                  NaN   
42398                               NaN                  NaN   

           production_countries release_date  revenue_musd  runtime   
30352  United States of America   2009-10-14           NaN     83.0  \
31596                     Italy   2008-01-01           NaN     89.0   
42398                       NaN   1997-01-02           NaN      NaN   

      spoken_languages    status tagline            title  vote_average   
30352          English       NaN     NaN  New Muslim Cool           NaN  \
31596         Italiano  Released     NaN    Just a Father           6.9   
42398              NaN  Released     NaN            Today           NaN   

       vote_count  
30352         0.0  
31596        24.0  
42398         0.0

In [102]:
df[(df["overview"].str.contains('No movie overview available') == True)]

#df[(df["overview"].str.contains('No movie overview available') == True)]["overview"]
##29780    No movie overview available, please add one at...
##Name: overview, dtype: object


belongs_to_collection  budget_musd    genres      id original_language   
29780                   NaN          NaN  Thriller  149868                fi  \

                                                overview  popularity   
29780  No movie overview available, please add one at...    0.339234  \

                            poster_path production_companies   
29780  /zlcFJINFCTKADcLF5aSVtSSkLn9.jpg                  NaN  \

      production_countries release_date  revenue_musd  runtime   
29780                  NaN   2012-07-13           NaN      NaN  \

      spoken_languages    status tagline title  vote_average  vote_count  
29780            suomi  Released     NaN  Hush           6.5         1.0

In [103]:
df[(df["overview"].str.contains('No movie overview available. ') == True)]

df[(df["overview"].str.contains('No movie overview available. ') == True)]["overview"]



29780    No movie overview available, please add one at...
Name: overview, dtype: object

In [104]:
###### 
###### 
df["overview"].value_counts(dropna=False).head(5)
###### 954 missing values NaN before
###### 1104 missing values NaN now


overview
NaN                                                                                                                                                                       1104
A few funny little novels about different aspects of life.                                                                                                                   3
Released                                                                                                                                                                     3
Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.       3
Adaptation of the Jane Austen novel.                                                                                                                                         3
Name: count, dtype: int64

In [105]:
###### No Overview

print(len(df[(df["overview"].str.contains('No overview') == True)]))
### 138
### 3
###### No movie overview available.

print(len(df[(df["overview"].str.contains('No movie overview available') == True)]))
### 4
### 1.
###### No movie overview available. with an extra space at the end

print(len(df[(df["overview"].str.contains('No movie overview available. ') == True)]))
### 4
### 1

3
1
1


In [106]:
#df[(df["overview"].str.contains('No movie overview available. ') == True)]
df[df["overview"].str.contains('No movie overview') == True]
### index 29780

belongs_to_collection  budget_musd    genres      id original_language   
29780                   NaN          NaN  Thriller  149868                fi  \

                                                overview  popularity   
29780  No movie overview available, please add one at...    0.339234  \

                            poster_path production_companies   
29780  /zlcFJINFCTKADcLF5aSVtSSkLn9.jpg                  NaN  \

      production_countries release_date  revenue_musd  runtime   
29780                  NaN   2012-07-13           NaN      NaN  \

      spoken_languages    status tagline title  vote_average  vote_count  
29780            suomi  Released     NaN  Hush           6.5         1.0

In [107]:
### Replacing Strings with missing values - specific str

#df["overview"].replace(to_replace="No overview found.", value=np.nan, inplace=True)
#df["overview"].replace(to_replace="No Overview", value=np.nan, inplace=True)
#df["overview"].replace(to_replace="No movie overview available.", value=np.nan, inplace=True)
#df["overview"].replace(to_replace=" ", value=np.nan, inplace=True)
#df["overview"].replace(to_replace="No overview yet.", value=np.nan, inplace=True)


In [108]:



#df["overview"].iloc[29780]
##'No movie overview available, please add one at themoviedb.org'

## Error
#df["overview"].iloc[29780].replace(to_replace="No movie overview available, please add one at themoviedb.org", value=np.nan, inplace=True)
## Correct way
df["overview"].replace(to_replace="No movie overview available, please add one at themoviedb.org", value=np.nan, inplace=True)


In [109]:
###### No Overview

print(len(df[(df["overview"].str.contains('No overview') == True)]))
### 138
### 3
###### No movie overview available.

print(len(df[(df["overview"].str.contains('No movie overview available') == True)]))
### 4
### 1
## 0
###### No movie overview available. with an extra space at the end

print(len(df[(df["overview"].str.contains('No movie overview available. ') == True)]))
### 4
### 1
## 0

3
0
0


In [110]:
df[(df["overview"].str.contains('No overview') == True)]["overview"]
##30352    No overview found
##31596          No overview
##42398         No overview.
##Name: overview, dtype: object

30352    No overview found
31596          No overview
42398         No overview.
Name: overview, dtype: object

In [111]:
### Replacing Strings with missing values - specific str

#df["overview"].replace(to_replace="No overview found.", value=np.nan, inplace=True)
#df["overview"].replace(to_replace="No Overview", value=np.nan, inplace=True)
#df["overview"].replace(to_replace="No movie overview available.", value=np.nan, inplace=True)
#df["overview"].replace(to_replace=" ", value=np.nan, inplace=True)
#df["overview"].replace(to_replace="No overview yet.", value=np.nan, inplace=True)

#df["overview"].replace(to_replace="No movie overview available, please add one at themoviedb.org", value=np.nan, inplace=True)

df["overview"].replace(to_replace=df[(df["overview"].str.contains('No overview') == True)]["overview"][30352], value=np.nan, inplace=True)
df["overview"].replace(to_replace=df[(df["overview"].str.contains('No overview') == True)]["overview"][31596], value=np.nan, inplace=True)
df["overview"].replace(to_replace=df[(df["overview"].str.contains('No overview') == True)]["overview"][42398], value=np.nan, inplace=True)



In [112]:
###### No Overview

print(len(df[(df["overview"].str.contains('No overview') == True)]))
### 138
### 3
###### No movie overview available.
### 0

print(len(df[(df["overview"].str.contains('No movie overview available') == True)]))
### 4
### 1
## 0
###### No movie overview available. with an extra space at the end

print(len(df[(df["overview"].str.contains('No movie overview available. ') == True)]))
### 4
### 1
## 0

0
0
0


##### tagline

In [113]:
###### 
###### 
df["tagline"].value_counts(dropna = False).head(50)
###### 25054 missing values NaN before
###### 4 with '-' that sign
###### 3 with "Drama"

tagline
NaN                                                                                                                      25054
Based on a true story.                                                                                                       7
Trust no one.                                                                                                                4
Be careful what you wish for.                                                                                                4
-                                                                                                                            4
Classic Albums                                                                                                               3
Some doors should never be opened.                                                                                           3
A Love Story                                                                                           

In [114]:
df[(df["tagline"].str.contains('-') == True)]


belongs_to_collection  budget_musd   
184                                         NaN        0.150  \
350    The Flintstones (Live-Action) Collection       46.000   
366                                         NaN        6.000   
385                                         NaN        0.045   
444                                         NaN          NaN   
...                                         ...          ...   
45237                                       NaN          NaN   
45266                                       NaN        2.000   
45326                                       NaN          NaN   
45327                                       NaN          NaN   
45350                                       NaN          NaN   

                      genres      id original_language   
184                   Comedy   36196                en  \
350    Fantasy|Comedy|Family     888                en   
366             Comedy|Drama   12280                en   
385             Action|Crime     315                en   
444                   Comedy   20239                en   
...                      ...     ...               ...   
45237         Comedy|Romance   69483                en   
45266                 Comedy  373247                en   
45326                  Drama  120831                en   
45327                    NaN  364865                en   
45350           Drama|Horror   28669                en   

                                                overview  popularity   
184    Although Mary has little income, she still fin...    1.165039  \
350    Modern Stone Age family the Flintstones hit th...   15.019586   
366    Henry Hackett is the editor of a New York City...    4.006063   
385    Three strippers seeking thrills encounter a yo...    4.220541   
444    Chronicling the controversial career of bad bo...    0.985441   
...                                                  ...         ...   
45237  Julia and William were married and soon separa...    0.419679   
45266  A black comedy set during the aftermath of the...    0.947866   
45326  In Imperial Russia, Anna Karenina falls in lov...    0.664602   
45327  Art, obsession and anxiety permeate a dilapida...    0.067670   
45350  Rasputin, a crazed and debauched monk wreaks h...    1.921686   

                            poster_path   
184    /iYM0EdHrcbu8rhkDKVBkDcZEo8t.jpg  \
350    /dnYXJZgstixBsOjF4JJrPCDRd2n.jpg   
366    /3FMfcgvjwgmyoT6Pp89wALzSUHT.jpg   
385    /u0YrGkpjL5H190qqEsQavZ2WrV5.jpg   
444    /jrpkn4GuBDS1Kh0lyR1UcXgeMi9.jpg   
...                                 ...   
45237  /aCADpnzne3ByjAXhwmqDfgkANve.jpg   
45266  /iHhkhBSx3rcR5cmz41zOMYA0d9t.jpg   
45326   /x7PcJWZisWAmXr4wUl2gEBestR.jpg   
45327  /cshjmSY7U9PgCnC2WVjRaYg14mu.jpg   
45350  /dRanLQi2WkTrqHvTz5TiGniOkKb.jpg   

                                    production_companies   
184                                    Party Productions  \
350    Universal Pictures|Amblin Entertainment|Hanna-...   
366             Imagine Entertainment|Universal Pictures   
385                                 Eve Productions Inc.   
444                                                  NaN   
...                                                  ...   
45237                          Metro-Goldwyn-Mayer (MGM)   
45266                                                NaN   
45326                          Metro-Goldwyn-Mayer (MGM)   
45327                                                NaN   
45350     Seven Arts Productions|Hammer Film Productions   

                          production_countries release_date  revenue_musd   
184                   United States of America   1995-06-09      0.472370  \
350                   United States of America   1994-05-26    341.631208   
366                   United States of America   1994-03-18           NaN   
385                   United States of America   1965-08-06           NaN   
444    United Kingdom|United States of America   1994-10-28           Na

In [115]:
###### Replacing the dash "-" with a missing value
###### 
df["tagline"].replace("-", np.nan, inplace=True)


In [116]:
###### 
###### 
df["tagline"].value_counts(dropna = False).head(50)
###### 25054 missing values NaN before
###### 25058 missing values NaN after
###### 0 with '-' that sign


tagline
NaN                                                                                     25058
Based on a true story.                                                                      7
Trust no one.                                                                               4
Be careful what you wish for.                                                               4
Who is John Galt?                                                                           3
Some doors should never be opened.                                                          3
Drama                                                                                       3
Documentary                                                                                 3
There is no turning back                                                                    3
The end is near.                                                                            3
Classic Albums                                      

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   belongs_to_collection  4491 non-null   object        
 1   budget_musd            8890 non-null   float64       
 2   genres                 43024 non-null  object        
 3   id                     45466 non-null  object        
 4   original_language      45455 non-null  object        
 5   overview               44358 non-null  object        
 6   popularity             45460 non-null  float64       
 7   poster_path            45080 non-null  object        
 8   production_companies   33585 non-null  object        
 9   production_countries   39178 non-null  object        
 10  release_date           45376 non-null  datetime64[ns]
 11  revenue_musd           7408 non-null   float64       
 12  runtime                43645 non-null  float64       
 13  s

## Removing Duplicates

Rows or films that are identical

In [118]:
### Each movie should be unique

### Decision: The first instance will be treated as the original
### Decision: All the instances beside the first one will be removed

df[df.duplicated(keep = False)]

df[df.duplicated(keep = False)].sort_values(by = "id")


belongs_to_collection  budget_musd   
676                     NaN          NaN  \
1465                    NaN          NaN   
14012                   NaN          NaN   
24844                   NaN          NaN   
19890                   NaN          NaN   
21165                   NaN          NaN   
13261                   NaN          NaN   
13375                   NaN          NaN   
16764                   NaN          NaN   
19925                   NaN          NaN   
21854                   NaN          NaN   
13220          Why We Fight          NaN   
35798          Why We Fight          NaN   
28860                   NaN          NaN   
13603                   NaN          NaN   
14000                   NaN          NaN   
22151                   NaN          NaN   
8068                    NaN          NaN   
9327                    NaN          NaN   
23044                   NaN          NaN   
17229                   NaN          NaN   
24164                   NaN          NaN   
45265                   NaN          NaN   
33184                   NaN         0.98   
40040                   NaN         0.98   
15702                   NaN          NaN   
29374                   NaN          NaN   
9165                    NaN          NaN   
7345                    NaN          NaN   
13946                   NaN          NaN   
40276                   NaN          NaN   
16167                   NaN          NaN   
38871                   NaN          NaN   

                                         genres      id original_language   
676                               Drama|Romance  105045                de  \
1465                              Drama|Romance  105045                de   
14012                              Comedy|Drama   11115                en   
24844                              Comedy|Drama   11115                en   
19890             Fantasy|Drama|Science Fiction  119916                en   
21165             Fantasy|Drama|Science Fiction  119916                en   
13261                          Thriller|Mystery  141971                fi   
13375                          Thriller|Mystery  141971                fi   
16764                          Thriller|Mystery  141971                fi   
19925           Drama|Science Fiction|Animation  152795                en   
21854           Drama|Science Fiction|Animation  152795                en   
13220                               Documentary  159849                en   
35798                               Documentary  159849                en   
28860                              Drama|Comedy  168538                en   
13603                              Drama|Comedy  168538                en   
14000             Action|Horror|Science Fiction   18440                en   
22151             Action|Horror|Science Fiction   18440                en   
8068   Adventure|Animation|Drama|Action|Foreign   23305                en   
9327   Adventure|Animation|Drama|Action|Foreign   23305                en   
23044                                     Drama   25541                da   
17229                                     Drama   25541                da   
24164                              Comedy|Drama  265189                sv   
45265                              Comedy|Drama  265189                sv   
33184                             Drama|Fantasy  298721                th   
40040                             Drama|Fantasy  298721                th   
15702                             Drama|Foreign   42495                en   
29374                             Drama|Foreign   42495                en   
9165                       Crime|Drama|Thriller    5511                fr   
7345                       Crime|Drama|Thriller    5511                fr   
13946                                    Comedy   97995                en   
40276                                    Comedy   97995                en   
16167            Action|Drama|Romance|Adventu

In [119]:
### Dropping all the duplicate instances besides the first one

df.drop_duplicates(inplace=True)


In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45449 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   belongs_to_collection  4490 non-null   object        
 1   budget_musd            8889 non-null   float64       
 2   genres                 43007 non-null  object        
 3   id                     45449 non-null  object        
 4   original_language      45438 non-null  object        
 5   overview               44341 non-null  object        
 6   popularity             45443 non-null  float64       
 7   poster_path            45063 non-null  object        
 8   production_companies   33573 non-null  object        
 9   production_countries   39164 non-null  object        
 10  release_date           45359 non-null  datetime64[ns]
 11  revenue_musd           7405 non-null   float64       
 12  runtime                43628 non-null  float64       
 13  spoken

In [121]:
###### Removing duplicates that have identical values in all columns
###### Focusing only on the id column
df[df.duplicated(subset = "id", keep = False)].sort_values(by = "id")

###### Example
###### 33826
###### 5865
###### Are similar with a difference in popularity


belongs_to_collection  budget_musd   
4114     Pokémon Collection    16.000000  \
44821    Pokémon Collection    16.000000   
20899                   NaN          NaN   
5710                    NaN          NaN   
23534                   NaN     3.512454   
4356                    NaN     3.512454   
44826    Pokémon Collection          NaN   
5535     Pokémon Collection          NaN   
15765                   NaN     0.002500   
11342                   NaN     0.002500   
30001                   NaN          NaN   
838                     NaN          NaN   
10419                   NaN     1.600000   
12066                   NaN     1.600000   
5130                    NaN    26.000000   
33743                   NaN    26.000000   
15074                   NaN     0.000004   
949                     NaN     0.000004   
5865                    NaN    30.000000   
33826                   NaN    30.000000   
26625                   NaN    10.000000   
9576                    NaN    10.000000   
11155                   NaN    40.000000   
20843                   NaN    40.000000   
2564                    NaN          NaN   
21116                   NaN          NaN   

                                                  genres      id   
4114           Adventure|Fantasy|Animation|Action|Family   10991  \
44821          Adventure|Fantasy|Animation|Action|Family   10991   
20899                                              Drama  109962   
5710                                               Drama  109962   
23534                                              Drama  110428   
4356                                               Drama  110428   
44826  Adventure|Fantasy|Animation|Science Fiction|Fa...   12600   
5535   Adventure|Fantasy|Animation|Science Fiction|Fa...   12600   
15765                               Drama|Comedy|Foreign   13209   
11342                               Drama|Comedy|Foreign   13209   
30001                                              Drama  132641   
838                                                Drama  132641   
10419                                Drama|Crime|Mystery   14788   
12066                                Drama|Crime|Mystery   14788   
5130           Adventure|Family|Science Fiction|Thriller   15028   
33743          Adventure|Family|Science Fiction|Thriller   15028   
15074                                  Drama|Romance|War   22649   
949                                    Drama|Romance|War   22649   
5865                 Comedy|Crime|Drama|Romance|Thriller    4912   
33826                Comedy|Crime|Drama|Romance|Thriller    4912   
26625                Drama|Horror|Music|Romance|TV Movie   69234   
9576                 Drama|Horror|Music|Romance|TV Movie   69234   
11155                                    Adventure|Drama   77221   
20843                                    Adventure|Drama   77221   
2564                                         Documentary   84198   
21116                                        Documentary   84198   

      original_language                                           overview   
4114                 ja  When Molly Hale's sadness of her father's disa...  \
44821                ja  When Molly Hale's sadness of her father's disa...   
20899                en  Two literary women compete for 20 years: one w...   
5710                 en  Two literary women compete for 20 years: one w...   
23534                fr  Winter, 1915. Confined by her family to an asy...   
4356                 fr  Winter, 1915. Confined by her family to an asy...   
44826                ja  All your favorite Pokémon characters are back,...   
5535                 ja  All your favorite Pokémon characters are back,...   
15765                fa  Since women are banned from soccer matches, Ir...   
11342                fa  Since women are banned from soccer matches, Ir...   
30001                ja  Ten years into a marriage, the wife is disappo...   
838                  ja  Ten years into a ma

In [122]:
###### Removing duplicates by the id column

df.drop_duplicates(subset = "id", inplace=True)


In [123]:
###### There are no more duplicates on the id column
df["id"].value_counts(dropna = False)


id
862       1
40777     1
107308    1
16247     1
99904     1
         ..
44399     1
10138     1
32084     1
42191     1
461257    1
Name: count, Length: 45436, dtype: int64

## Handling Missing Values & Removing ObervationsRows


In [124]:
###### missing values

#df.info()
df.isna().sum()


belongs_to_collection    40948
budget_musd              36556
genres                    2442
id                           0
original_language           11
overview                  1108
popularity                   6
poster_path                386
production_companies     11874
production_countries      6285
release_date                90
revenue_musd             38038
runtime                   1821
spoken_languages          3956
status                      87
tagline                  25039
title                        6
vote_average              2902
vote_count                   6
dtype: int64

In [125]:
###### See the films where the title is missing
df[df["title"].isna()]

###### The movie id is also missing in one of this
###### These films have similarities. They do not have a lot of information. A lot of missing values are present


belongs_to_collection  budget_musd   
19729                          NaN          NaN  \
19730                          NaN          NaN   
29502  Mardock Scramble Collection          NaN   
29503                          NaN          NaN   
35586                          NaN          NaN   
35587                          NaN          NaN   

                                                  genres          id   
19729                              Action|Thriller|Drama       82663  \
19730  Carousel Productions|Vision View Entertainment...  1997-08-20   
29502                          Animation|Science Fiction      122662   
29503  Aniplex|GoHands|BROSTA TV|Mardock Scramble Pro...  2012-09-29   
35586             TV Movie|Action|Horror|Science Fiction      249260   
35587  Odyssey Media|Pulser Productions|Rogue State|T...  2014-01-01   

      original_language                                           overview   
19729                en  British soldiers force a recently captured IRA...  \
19730             104.0                                           Released   
29502                ja         Third film of the Mardock Scramble series.   
29503              68.0                                           Released   
35586                en  A group of skiers are terrorized during spring...   
35587              82.0                                           Released   

       popularity                          poster_path production_companies   
19729         NaN                                  NaN                  NaN  \
19730         NaN                         Midnight Man                  NaN   
29502         NaN                                  NaN                  NaN   
29503         NaN  Mardock Scramble: The Third Exhaust                  NaN   
35586         NaN                                  NaN                  NaN   
35587         NaN                     Avalanche Sharks                  NaN   

      production_countries release_date  revenue_musd  runtime   
19729                  NaN          NaT           NaN      NaN  \
19730                  NaN          NaT           NaN      NaN   
29502                  NaN          NaT           NaN      NaN   
29503                  NaN          NaT           NaN      NaN   
35586                  NaN          NaT           NaN      NaN   
35587                  NaN          NaT           NaN      NaN   

      spoken_languages status tagline title  vote_average  vote_count  
19729              NaN    NaN     NaN   NaN           NaN         NaN  
19730              NaN    NaN     NaN   NaN           NaN         NaN  
29502              NaN    NaN     NaN   NaN           NaN         NaN  
29503              NaN    NaN     NaN   NaN           NaN         NaN  
35586              NaN    NaN     NaN   NaN           NaN         NaN  
35587              NaN    NaN     NaN   NaN           NaN         NaN

In [126]:
###### Dropping all rows where there are missing values on the id and the title columns

df.dropna(subset = ["id", "title"], inplace=True)


In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45430 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   belongs_to_collection  4487 non-null   object        
 1   budget_musd            8880 non-null   float64       
 2   genres                 42988 non-null  object        
 3   id                     45430 non-null  object        
 4   original_language      45419 non-null  object        
 5   overview               44322 non-null  object        
 6   popularity             45430 non-null  float64       
 7   poster_path            45047 non-null  object        
 8   production_companies   33562 non-null  object        
 9   production_countries   39151 non-null  object        
 10  release_date           45346 non-null  datetime64[ns]
 11  revenue_musd           7398 non-null   float64       
 12  runtime                43615 non-null  float64       
 13  spoken

In [128]:
###### Check how many non-missing values exist in each row/film
df.notna().sum(axis = 1)

###### 0        18
###### 1        18
###### For the first and second movie there are 18 non-missing values

df.notna().sum(axis = 1).value_counts().sort_values(ascending=False)

###### For the majority there are 15, 16, 14, 17, 18 non-missing values
###### There are 4 movies where we only have 6 non-missing values, meaning there are 12 missing values


15    12522
16    11454
14     5424
17     4265
18     3859
13     3039
12     1891
19     1132
11     1020
10      512
9       184
8       103
7        21
6         4
Name: count, dtype: int64

In [129]:
###### See the rows where there are only 6 non-missing values
df[df.notna().sum(axis=1) == 6]


belongs_to_collection  budget_musd genres      id original_language   
18038                   NaN          NaN    NaN  344741                pl  \
20166                   NaN          NaN    NaN  139909                fi   
41718                   NaN          NaN    NaN  216550                de   
44978                   NaN          NaN    NaN  398295                pt   

      overview  popularity poster_path production_companies   
18038      NaN    0.000000         NaN                  NaN  \
20166      NaN    0.000127         NaN                  NaN   
41718      NaN    0.000000         NaN                  NaN   
44978      NaN    0.000331         NaN                  NaN   

      production_countries release_date  revenue_musd  runtime   
18038                  NaN          NaT           NaN      NaN  \
20166                  NaN          NaT           NaN      NaN   
41718                  NaN          NaT           NaN      NaN   
44978                  NaN          NaT           NaN      NaN   

      spoken_languages    status tagline   
18038              NaN  Released     NaN  \
20166              NaN  Released     NaN   
41718              NaN  Released     NaN   
44978              NaN  Released     NaN   

                                        title  vote_average  vote_count  
18038                              Pajęczarki           NaN         0.0  
20166                            Aurinkotuuli           NaN         0.0  
41718  Dolpo Tulku - Heimkehr in den Himalaya           NaN         0.0  
44978                               Mundo Cão           NaN         0.0

In [130]:
###### 
df.dropna(thresh=10, inplace=True)


In [131]:
###### 
df.notna().sum(axis = 1).value_counts().sort_values(ascending=False)


15    12522
16    11454
14     5424
17     4265
18     3859
13     3039
12     1891
19     1132
11     1020
10      512
Name: count, dtype: int64

## Other

In [132]:
df["status"].value_counts()

status
Released           44691
Rumored              226
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: count, dtype: int64

In [133]:
###### Only interested in the Released movies
df = df.loc[df["status"] == "Released"].copy()



In [134]:
df.head(3)

belongs_to_collection  budget_musd                    genres     id   
0       Toy Story Collection         30.0   Animation|Comedy|Family    862  \
1                        NaN         65.0  Adventure|Fantasy|Family   8844   
2  Grumpy Old Men Collection          NaN            Romance|Comedy  15602   

  original_language                                           overview   
0                en  Led by Woody, Andy's toys live happily in his ...  \
1                en  When siblings Judy and Peter discover an encha...   
2                en  A family wedding reignites the ancient feud be...   

   popularity                       poster_path   
0   21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  \
1   17.015539  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   
2   11.712900  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg   

                                production_companies   
0                            Pixar Animation Studios  \
1  TriStar Pictures|Teitler Film|Interscope Commu...   
2                        Warner Bros.|Lancaster Gate   

       production_countries release_date  revenue_musd  runtime   
0  United States of America   1995-10-30    373.554033     81.0  \
1  United States of America   1995-12-15    262.797249    104.0   
2  United States of America   1995-12-22           NaN    101.0   

   spoken_languages    status   
0           English  Released  \
1  English|Français  Released   
2           English  Released   

                                             tagline             title   
0                                                NaN         Toy Story  \
1          Roll the dice and unleash the excitement!           Jumanji   
2  Still Yelling. Still Fighting. Still Ready for...  Grumpier Old Men   

   vote_average  vote_count  
0           7.7      5415.0  
1           6.9      2413.0  
2           6.5        92.0

In [135]:
###### Dropping the status column since I already selected all of the Released films only
df.drop(columns = ["status"], inplace=True)


In [136]:
df.columns

Index(['belongs_to_collection', 'budget_musd', 'genres', 'id',
       'original_language', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue_musd', 'runtime', 'spoken_languages', 'tagline', 'title',
       'vote_average', 'vote_count'],
      dtype='object')

In [137]:
###### 
###### Selecting specific cols
col = ["id", "title", "tagline", "release_date", "genres", "belongs_to_collection",
       "original_language", "budget_musd", "revenue_musd", "production_companies",
       "production_countries", "vote_count", "vote_average", "popularity", "runtime",
       "overview", "spoken_languages", "poster_path"]


In [138]:
###### All rows, specific cols
df = df.loc[:, col]



In [139]:
df.head()

id                        title   
0    862                    Toy Story  \
1   8844                      Jumanji   
2  15602             Grumpier Old Men   
3  31357            Waiting to Exhale   
4  11862  Father of the Bride Part II   

                                             tagline release_date   
0                                                NaN   1995-10-30  \
1          Roll the dice and unleash the excitement!   1995-12-15   
2  Still Yelling. Still Fighting. Still Ready for...   1995-12-22   
3  Friends are the people who let you be yourself...   1995-12-22   
4  Just When His World Is Back To Normal... He's ...   1995-02-10   

                     genres           belongs_to_collection original_language   
0   Animation|Comedy|Family            Toy Story Collection                en  \
1  Adventure|Fantasy|Family                             NaN                en   
2            Romance|Comedy       Grumpy Old Men Collection                en   
3      Comedy|Drama|Romance                             NaN                en   
4                    Comedy  Father of the Bride Collection                en   

   budget_musd  revenue_musd   
0         30.0    373.554033  \
1         65.0    262.797249   
2          NaN           NaN   
3         16.0     81.452156   
4          NaN     76.578911   

                                production_companies   
0                            Pixar Animation Studios  \
1  TriStar Pictures|Teitler Film|Interscope Commu...   
2                        Warner Bros.|Lancaster Gate   
3             Twentieth Century Fox Film Corporation   
4          Sandollar Productions|Touchstone Pictures   

       production_countries  vote_count  vote_average  popularity  runtime   
0  United States of America      5415.0           7.7   21.946943     81.0  \
1  United States of America      2413.0           6.9   17.015539    104.0   
2  United States of America        92.0           6.5   11.712900    101.0   
3  United States of America        34.0           6.1    3.859495    127.0   
4  United States of America       173.0           5.7    8.387519    106.0   

                                            overview  spoken_languages   
0  Led by Woody, Andy's toys live happily in his ...           English  \
1  When siblings Judy and Peter discover an encha...  English|Français   
2  A family wedding reignites the ancient feud be...           English   
3  Cheated on, mistreated and stepped on, the wom...           English   
4  Just when George Banks has recovered from his ...           English   

                        poster_path  
0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  
1  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg  
2  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg  
3  /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg  
4  /e64sOI48hQXyru7naBFyssKFxVd.jpg

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44691 entries, 0 to 45465
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   id                     44691 non-null  object        
 1   title                  44691 non-null  object        
 2   tagline                20284 non-null  object        
 3   release_date           44657 non-null  datetime64[ns]
 4   genres                 42586 non-null  object        
 5   belongs_to_collection  4463 non-null   object        
 6   original_language      44681 non-null  object        
 7   budget_musd            8854 non-null   float64       
 8   revenue_musd           7385 non-null   float64       
 9   production_companies   33356 non-null  object        
 10  production_countries   38835 non-null  object        
 11  vote_count             44691 non-null  float64       
 12  vote_average           42077 non-null  float64       
 13  popula

In [141]:
df.head(3)

id             title                                            tagline   
0    862         Toy Story                                                NaN  \
1   8844           Jumanji          Roll the dice and unleash the excitement!   
2  15602  Grumpier Old Men  Still Yelling. Still Fighting. Still Ready for...   

  release_date                    genres      belongs_to_collection   
0   1995-10-30   Animation|Comedy|Family       Toy Story Collection  \
1   1995-12-15  Adventure|Fantasy|Family                        NaN   
2   1995-12-22            Romance|Comedy  Grumpy Old Men Collection   

  original_language  budget_musd  revenue_musd   
0                en         30.0    373.554033  \
1                en         65.0    262.797249   
2                en          NaN           NaN   

                                production_companies   
0                            Pixar Animation Studios  \
1  TriStar Pictures|Teitler Film|Interscope Commu...   
2                        Warner Bros.|Lancaster Gate   

       production_countries  vote_count  vote_average  popularity  runtime   
0  United States of America      5415.0           7.7   21.946943     81.0  \
1  United States of America      2413.0           6.9   17.015539    104.0   
2  United States of America        92.0           6.5   11.712900    101.0   

                                            overview  spoken_languages   
0  Led by Woody, Andy's toys live happily in his ...           English  \
1  When siblings Judy and Peter discover an encha...  English|Français   
2  A family wedding reignites the ancient feud be...           English   

                        poster_path  
0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg  
1  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg  
2  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg

In [142]:
###### Reseting index
df.reset_index(drop = True, inplace = True)


In [143]:
df.head(1)

id      title tagline release_date                   genres   
0  862  Toy Story     NaN   1995-10-30  Animation|Comedy|Family  \

  belongs_to_collection original_language  budget_musd  revenue_musd   
0  Toy Story Collection                en         30.0    373.554033  \

      production_companies      production_countries  vote_count   
0  Pixar Animation Studios  United States of America      5415.0  \

   vote_average  popularity  runtime   
0           7.7   21.946943     81.0  \

                                            overview spoken_languages   
0  Led by Woody, Andy's toys live happily in his ...          English  \

                        poster_path  
0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg

In [144]:
###### Modifying poster_path to get full url

df["poster_path"][0]
######'/rhIRbceoE9lR4veEXuwCC2wARtG.jpg'


'/rhIRbceoE9lR4veEXuwCC2wARtG.jpg'

In [145]:
###### Modifying poster_path to get full url
base_poster_url = 'http://image.tmdb.org/t/p/w185/'
df["poster_path"] = "<img src='" + base_poster_url + df["poster_path"] + "' style='height:100px;'>"



In [146]:
###### Verifying full url
df["poster_path"][0]
###### "<img src='http://image.tmdb.org/t/p/w185//rhIRbceoE9lR4veEXuwCC2wARtG.jpg' style='height:100px;'>"


"<img src='http://image.tmdb.org/t/p/w185//rhIRbceoE9lR4veEXuwCC2wARtG.jpg' style='height:100px;'>"

In [143]:
### Saving Preprocessed Dataset
###### 
#df.to_csv("/xx/xx/Desktop/movies_metadata.csv", index=False)
#df.to_csv("/xx/xx/Desktop/movies_complete.csv", index=False)



In [144]:
###### 
###### 
#df_metadata0 = df.to_csv("/xx/xx/Desktop/movies_metadata.csv")
#df_movies_complete0 = df.to_csv("/xx/xx/Desktop/movies_complete.csv")



In [147]:
df_movies_complete0.info()

NameError: name 'df_movies_complete0' is not defined

In [146]:
df_movies_complete0.isna().sum()

id                           0
title                        0
tagline                  24407
release_date                34
genres                    2105
belongs_to_collection    40228
original_language           10
budget_musd              35837
revenue_musd             37306
production_companies     11335
production_countries      5856
vote_count                   0
vote_average              2614
popularity                   0
runtime                   1512
overview                   951
spoken_languages          3597
poster_path                224
dtype: int64

In [147]:
df_movies_complete0.head(2)

## Avatar https://www.themoviedb.org/movie/19995-avatar
## Avatar https://www.themoviedb.org/t/p/w1280/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg


id      title                                    tagline release_date   
0   862  Toy Story                                        NaN   1995-10-30  \
1  8844    Jumanji  Roll the dice and unleash the excitement!   1995-12-15   

                     genres belongs_to_collection original_language   
0   Animation|Comedy|Family  Toy Story Collection                en  \
1  Adventure|Fantasy|Family                   NaN                en   

   budget_musd  revenue_musd   
0         30.0    373.554033  \
1         65.0    262.797249   

                                production_companies   
0                            Pixar Animation Studios  \
1  TriStar Pictures|Teitler Film|Interscope Commu...   

       production_countries  vote_count  vote_average  popularity  runtime   
0  United States of America      5415.0           7.7   21.946943     81.0  \
1  United States of America      2413.0           6.9   17.015539    104.0   

                                            overview  spoken_languages   
0  Led by Woody, Andy's toys live happily in his ...           English  \
1  When siblings Judy and Peter discover an encha...  English|Français   

                                         poster_path  
0  <img src='http://image.tmdb.org/t/p/w185//rhIR...  
1  <img src='http://image.tmdb.org/t/p/w185//vzmL...